import "./globals.css";
import { Inter, Exo } from '@next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Optional: Define a CSS variable
});

const exo = Exo({
  subsets: ['latin'],
  variable: '--font-exo', // Optional: Define a CSS variable
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${exo.variable} font-inter bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
